CREATE TRIGGER TRG_BOOK_TICEKT
BEFORE UPDATE OF BOOKING_ID ON TICKET
REFERENCING OLD AS O NEW AS N
FOR EACH ROW MODE DB2SQL
BEGIN
	DECLARE CONCERT_BEGIN TIMESTAMP; 	-- Concert begin time 
	DECLARE BOOKTIME TIMESTAMP;		 	-- Booking time
	
	-- Convert date to timestamp
	SET CONCERT_BEGIN = ( SELECT TIMESTAMP_ISO( DATE( Con_Date ) )
						  FROM CONCERT C 
						  WHERE N.CON_ID = C.CON_ID 
						  FETCH FIRST ROWS ONLY );
	SET BOOKTIME = ( SELECT Booking_Time 
					 FROM BOOKING B 
					 WHERE N.BOOKING_ID = B.BOOKING_ID
					 FETCH FIRST ROWS ONLY );
	
	IF ( O.BOOKING_ID IS NOT NULL ) OR ( BOOKTIME > CONCERT_BEGIN )
		THEN
		CALL DBMS_OUTPUT.PUT( 'Ticket selected is booked or invalid to be booked.' );
		CALL DBMS_OUTPUT.NEW_LINE;
		SET N.BOOKING_ID = O.BOOKING_ID;
	END IF;
END@
