CREATE PROCEDURE spAvailableTickets( IN concertID CHAR(6) )
    BEGIN
        DECLARE c cursor with return for
            SELECT DISTINCT TICKET.TICKET_ID AS AVAILABLE_TICKETS, TICKET.TICKET_TYPE, TICKET.TICKET_PRICE
            FROM TICKET, BOOKING, CONCERT
            WHERE TICKET.BOOKING_ID IS NULL
            AND concertID = CONCERT.CON_ID
            AND concertID = TICKET.CON_ID
            ORDER BY TICKET.TICKET_ID;
        OPEN c;
    END@

CREATE PROCEDURE spTheatreSchedule( IN theatreID CHAR(6), concertDate DATE )
    BEGIN
        DECLARE c cursor with return for
            SELECT DISTINCT CONCERT.CON_TITLE, CONCERT.CON_TIMESTART, CONCERT.CON_TIMEEND
            FROM CONCERT, THEATRE
            WHERE theatreID = THEATRE.THEATRE_ID
            AND theatreID = CONCERT.THEATRE_ID
            AND concertDate = CONCERT.CON_DATE
            ORDER BY CONCERT.CON_TIMESTART;
        OPEN c;
    END@

CREATE PROCEDURE spTop2Concerts( IN startDate DATE, endDate DATE )
    BEGIN
        DECLARE c cursor with return for
            SELECT CONCERT.CON_TITLE, COUNT(TICKET.TICKET_ID) AS TICKETS_SOLD
            FROM CONCERT, TICKET, BOOKING
            WHERE CONCERT.CON_DATE BETWEEN startDate AND endDate
            AND BOOKING.BOOKING_ID = TICKET.BOOKING_ID
            AND  CONCERT.CON_ID = TICKET.CON_ID
            GROUP BY CONCERT.CON_TITLE
            ORDER BY COUNT(TICKET.TICKET_ID) DESC
            LIMIT 2;
        OPEN c;
    END@
	
CREATE PROCEDURE spTop5Agents( IN startDate DATE, endDate DATE )
    BEGIN
        DECLARE c cursor with return for
            SELECT AGENT.AGENT_FNAME, AGENT.AGENT_LNAME, COUNT(TICKET.TICKET_ID) AS TICKETS_SOLD
            FROM AGENT, TICKET, BOOKING, CONCERT
            WHERE CONCERT.CON_DATE BETWEEN startDate AND endDate
            AND BOOKING.BOOKING_ID = TICKET.BOOKING_ID
            AND  AGENT.AGENT_ID = BOOKING.AGENT_ID
            AND CONCERT.CON_ID = TICKET.CON_ID
            GROUP BY AGENT.AGENT_FNAME, AGENT.AGENT_LNAME
            ORDER BY COUNT(TICKET.TICKET_ID) DESC
            LIMIT 5;
        OPEN c;
    END@

CREATE PROCEDURE spTop5Customers( IN startDate DATE, endDate DATE )
    BEGIN
        DECLARE c cursor with return for
            SELECT CUSTOMER.CUS_FNAME, CUSTOMER.CUS_LNAME, COUNT(TICKET.TICKET_ID) AS TICKETS_BOUGHT
            FROM CUSTOMER, TICKET, BOOKING, CONCERT
            WHERE CONCERT.CON_DATE BETWEEN startDate AND endDate
            AND BOOKING.BOOKING_ID = TICKET.BOOKING_ID
            AND  CUSTOMER.CUS_ID = BOOKING.CUS_ID
            AND CONCERT.CON_ID = TICKET.CON_ID
            GROUP BY CUSTOMER.CUS_FNAME, CUSTOMER.CUS_LNAME
            ORDER BY COUNT(TICKET.TICKET_ID) DESC
            LIMIT 5;
        OPEN c;
    END@