--NUMBER OF AGENT SOLD
CREATE VIEW NO_TICKET_SOLD AS
SELECT  AGENT_FNAME, 
		AGENT_LNAME,
		COUNT(NT.TICKET_ID) AS NORMAL_SOLD,
		COUNT(VT.TICKET_ID) AS VIP_SOLD,
		COUNT(NT.TICKET_ID) + COUNT(VT.TICKET_ID) AS TOTAL_SOLD
FROM TICKET TK
		LEFT OUTER JOIN NORMAL_TICKET NT
		ON TK.TICKET_ID = NT.TICKET_ID
		AND TK.CON_ID = NT.CON_ID
		LEFT OUTER JOIN VIP_TICKET VT
		ON TK.TICKET_ID = VT.TICKET_ID
		AND TK.CON_ID = VT.CON_ID
		LEFT OUTER JOIN BOOKING BK
		ON BK.BOOKING_ID = TK.BOOKING_ID
		LEFT OUTER JOIN AGENT AG
		ON BK.AGENT_ID = AG.AGENT_ID
WHERE TK.BOOKING_ID IS NOT NULL
GROUP BY ( AGENT_FNAME, AGENT_LNAME )@


--NUMBER OF TICKET PURCHASE BY A CUSTOMER 
CREATE VIEW CUSTOMER_PURCHASE AS
SELECT  CUS_FNAME, 
		CUS_LNAME,
		COUNT(NT.TICKET_ID) AS NORMAL_BOUGHT,
		COUNT(VT.TICKET_ID) AS VIP_BOUGHT,
		COUNT(NT.TICKET_ID) + COUNT(VT.TICKET_ID) AS TOTAL_TICKET_BOUGHT
FROM TICKET TK
		LEFT OUTER JOIN NORMAL_TICKET NT
		ON TK.TICKET_ID = NT.TICKET_ID
		AND TK.CON_ID = NT.CON_ID
		LEFT OUTER JOIN VIP_TICKET VT
		ON TK.TICKET_ID = VT.TICKET_ID
		AND TK.CON_ID = VT.CON_ID
		LEFT OUTER JOIN BOOKING BK
		ON BK.BOOKING_ID = TK.BOOKING_ID
		LEFT OUTER JOIN CUSTOMER CS 
		ON BK.CUS_ID = CS.CUS_ID
WHERE TK.BOOKING_ID IS NOT NULL
GROUP BY ( CUS_FNAME, CUS_LNAME )@


--normal ticket sold
CREATE VIEW NORM_TICKET_SOLD AS
SELECT CON_TITLE, 
	   COUNT( NT.TICKET_ID ) AS NORMAL_SOLD,
	   SEAT_CAPACITY - VIP_COUNT AS NORMAL_CAPACITY,
	   ( CAST( ( ( ( CAST( COUNT( NT.TICKET_ID ) AS DECIMAL ( 7, 3 ) ) ) / (SEAT_CAPACITY - VIP_COUNT) ) * 100) AS DECIMAL ( 5, 2 ) ) ) AS SOLD_PERCENT
FROM NORMAL_TICKET NT
		LEFT OUTER JOIN CONCERT C
		ON C.CON_ID = NT.CON_ID
		LEFT OUTER JOIN THEATRE TT
		ON C.THEATRE_ID = TT.THEATRE_ID
		LEFT OUTER JOIN TICKET T
		ON NT.TICKET_ID = T.TICKET_ID
		AND NT.CON_ID = T.CON_ID
WHERE T.BOOKING_ID IS NOT NULL
GROUP BY ( CON_TITLE, SEAT_CAPACITY, VIP_COUNT )@


--AMOUNT OF TICKET AVAILABLE
CREATE VIEW SEAT_AVAILABLE AS
SELECT  CON_TITLE,  
		COUNT(NT.TICKET_ID) AS NORMAL_AVAILABLE,
		COUNT(VT.TICKET_ID) AS VIP_AVAILABLE
FROM TICKET T
		LEFT OUTER JOIN CONCERT C
		ON C.CON_ID = T.CON_ID
		LEFT OUTER JOIN NORMAL_TICKET NT
		ON T.TICKET_ID = NT.TICKET_ID
		AND T.CON_ID = NT.CON_ID
		LEFT OUTER JOIN VIP_TICKET VT
		ON T.TICKET_ID = VT.TICKET_ID
		AND T.CON_ID = VT.CON_ID
WHERE T.BOOKING_ID IS NULL
GROUP BY ( CON_TITLE)@


--total ticket sold
CREATE VIEW TOTAL_TICKET_SOLD AS
SELECT CON_TITLE, 
	   COUNT( TICKET_ID ) AS TICKETS_SOLD,
	   SEAT_CAPACITY,
	   ( CAST( ( ( ( CAST( COUNT( TICKET_ID ) AS DECIMAL ( 7, 3 ) ) ) / SEAT_CAPACITY ) * 100) AS DECIMAL ( 5, 2 ) ) ) AS SOLD_PERCENT
FROM TICKET T
		LEFT OUTER JOIN CONCERT C
		ON C.CON_ID = T.CON_ID
		LEFT OUTER JOIN THEATRE TT
		ON C.THEATRE_ID = TT.THEATRE_ID
WHERE T.BOOKING_ID IS NOT NULL
GROUP BY ( CON_TITLE, SEAT_CAPACITY )@


--vip ticket sold
CREATE VIEW VIP_TICKET_SOLD AS
SELECT CON_TITLE, 
	   COUNT( VT.TICKET_ID ) AS VIP_SOLD,
	   VIP_COUNT AS VIP_CAPACITY,
	   ( CAST( ( ( ( CAST( COUNT( VT.TICKET_ID ) AS DECIMAL ( 7, 3 ) ) ) / (VIP_COUNT) ) * 100) AS DECIMAL ( 5, 2 ) ) ) AS SOLD_PERCENT
FROM VIP_TICKET VT
		LEFT OUTER JOIN CONCERT C
		ON C.CON_ID = VT.CON_ID
		LEFT OUTER JOIN THEATRE TT
		ON C.THEATRE_ID = TT.THEATRE_ID
		LEFT OUTER JOIN TICKET T
		ON VT.TICKET_ID = T.TICKET_ID
		AND VT.CON_ID = T.CON_ID
WHERE T.BOOKING_ID IS NOT NULL
GROUP BY ( CON_TITLE, VIP_COUNT )@