CREATE TRIGGER TRG_CALC_BOOKING_PRICE
AFTER UPDATE OF BOOKING_ID ON TICKET
REFERENCING NEW AS N
FOR EACH ROW MODE DB2SQL
UPDATE BOOKING B
SET TOTAL_PRICE = ( SELECT SUM( TICKET_PRICE )
					FROM TICKET 
					WHERE TICKET.BOOKING_ID = N.BOOKING_ID )
WHERE N.BOOKING_ID = B.BOOKING_ID@