CREATE PROCEDURE spTop5Customers( IN startDate DATE, endDate DATE )
    BEGIN
        DECLARE c cursor with return for
            SELECT CUSTOMER.CUS_FNAME, CUSTOMER.CUS_LNAME, COUNT(TICKET.TICKET_ID) AS TICKETS_BOUGHT
            FROM CUSTOMER, TICKET, BOOKING, CONCERT
            WHERE CONCERT.CON_DATE BETWEEN startDate AND endDate
            AND BOOKING.BOOKING_ID = TICKET.BOOKING_ID
            AND  CUSTOMER.CUS_ID = BOOKING.CUS_ID
            AND CONCERT.CON_ID = TICKET.CON_ID
            GROUP BY CUSTOMER.CUS_FNAME, CUSTOMER.CUS_LNAME
            ORDER BY COUNT(TICKET.TICKET_ID) DESC
            LIMIT 5;
        OPEN c;
    END@