CREATE PROCEDURE spTop5Agents( IN startDate DATE, endDate DATE )
    BEGIN
        DECLARE c cursor with return for
            SELECT AGENT.AGENT_FNAME, AGENT.AGENT_LNAME, COUNT(TICKET.TICKET_ID) AS TICKETS_SOLD
            FROM AGENT, TICKET, BOOKING, CONCERT
            WHERE CONCERT.CON_DATE BETWEEN startDate AND endDate
            AND BOOKING.BOOKING_ID = TICKET.BOOKING_ID
            AND  AGENT.AGENT_ID = BOOKING.AGENT_ID
            AND CONCERT.CON_ID = TICKET.CON_ID
            GROUP BY AGENT.AGENT_FNAME, AGENT.AGENT_LNAME
            ORDER BY COUNT(TICKET.TICKET_ID) DESC
            LIMIT 5;
        OPEN c;
    END@