--NUMBER OF TICKET PURCHASE BY A CUSTOMER 
CREATE VIEW CUSTOMER_PURCHASE AS
SELECT  CUS_FNAME, 
		CUS_LNAME,
		COUNT(NT.TICKET_ID) AS NORMAL_BOUGHT,
		COUNT(VT.TICKET_ID) AS VIP_BOUGHT,
		COUNT(NT.TICKET_ID) + COUNT(VT.TICKET_ID) AS TOTAL_TICKET_BOUGHT
FROM TICKET TK
		LEFT OUTER JOIN NORMAL_TICKET NT
		ON TK.TICKET_ID = NT.TICKET_ID
		AND TK.CON_ID = NT.CON_ID
		LEFT OUTER JOIN VIP_TICKET VT
		ON TK.TICKET_ID = VT.TICKET_ID
		AND TK.CON_ID = VT.CON_ID
		LEFT OUTER JOIN BOOKING BK
		ON BK.BOOKING_ID = TK.BOOKING_ID
		LEFT OUTER JOIN CUSTOMER CS 
		ON BK.CUS_ID = CS.CUS_ID
WHERE TK.BOOKING_ID IS NOT NULL
GROUP BY ( CUS_FNAME, CUS_LNAME )@



