--AMOUNT OF TICKET AVAILABLE
CREATE VIEW SEAT_AVAILABLE AS
SELECT  CON_TITLE,  
		COUNT(NT.TICKET_ID) AS NORMAL_AVAILABLE,
		COUNT(VT.TICKET_ID) AS VIP_AVAILABLE
FROM TICKET T
		LEFT OUTER JOIN CONCERT C
		ON C.CON_ID = T.CON_ID
		LEFT OUTER JOIN NORMAL_TICKET NT
		ON T.TICKET_ID = NT.TICKET_ID
		AND T.CON_ID = NT.CON_ID
		LEFT OUTER JOIN VIP_TICKET VT
		ON T.TICKET_ID = VT.TICKET_ID
		AND T.CON_ID = VT.CON_ID
WHERE T.BOOKING_ID IS NULL
GROUP BY ( CON_TITLE)@