--normal ticket sold
CREATE VIEW NORM_TICKET_SOLD AS
SELECT CON_TITLE, 
	   COUNT( NT.TICKET_ID ) AS NORMAL_SOLD,
	   SEAT_CAPACITY - VIP_COUNT AS NORMAL_CAPACITY,
	   ( CAST( ( ( ( CAST( COUNT( NT.TICKET_ID ) AS DECIMAL ( 7, 3 ) ) ) / (SEAT_CAPACITY - VIP_COUNT) ) * 100) AS DECIMAL ( 5, 2 ) ) ) AS SOLD_PERCENT
FROM NORMAL_TICKET NT
		LEFT OUTER JOIN CONCERT C
		ON C.CON_ID = NT.CON_ID
		LEFT OUTER JOIN THEATRE TT
		ON C.THEATRE_ID = TT.THEATRE_ID
		LEFT OUTER JOIN TICKET T
		ON NT.TICKET_ID = T.TICKET_ID
		AND NT.CON_ID = T.CON_ID
WHERE T.BOOKING_ID IS NOT NULL
GROUP BY ( CON_TITLE, SEAT_CAPACITY, VIP_COUNT )@
