--vip ticket sold
CREATE VIEW VIP_TICKET_SOLD AS
SELECT CON_TITLE, 
	   COUNT( VT.TICKET_ID ) AS VIP_SOLD,
	   VIP_COUNT AS VIP_CAPACITY,
	   ( CAST( ( ( ( CAST( COUNT( VT.TICKET_ID ) AS DECIMAL ( 7, 3 ) ) ) / (VIP_COUNT) ) * 100) AS DECIMAL ( 5, 2 ) ) ) AS SOLD_PERCENT
FROM VIP_TICKET VT
		LEFT OUTER JOIN CONCERT C
		ON C.CON_ID = VT.CON_ID
		LEFT OUTER JOIN THEATRE TT
		ON C.THEATRE_ID = TT.THEATRE_ID
		LEFT OUTER JOIN TICKET T
		ON VT.TICKET_ID = T.TICKET_ID
		AND VT.CON_ID = T.CON_ID
WHERE T.BOOKING_ID IS NOT NULL
GROUP BY ( CON_TITLE, VIP_COUNT )@