--AMOUNT OF TICKET LEFT
CREATE VIEW SEAT_LEFT AS
SELECT  CON_TITLE,  
COUNT(NT.TICKET_ID) AS NORMAL_LEFT,
COUNT(VT.TICKET_ID) AS VIP_LEFT
FROM TICKET T
LEFT OUTER JOIN CONCERT C
ON C.CON_ID = T.CON_ID
LEFT OUTER JOIN THEATRE TT
ON C.THEATRE_ID = TT.THEATRE_ID
LEFT OUTER JOIN NORMAL_TICKET NT
ON T.TICKET_ID = NT.TICKET_ID
AND T.CON_ID = NT.CON_ID
LEFT OUTER JOIN VIP_TICKET VT
ON T.TICKET_ID = VT.TICKET_ID
AND T.CON_ID = VT.CON_ID
LEFT OUTER JOIN BOOKING B
ON B.BOOKING_ID = T.BOOKING_ID
WHERE T.BOOKING_ID IS NULL
GROUP BY ( CON_TITLE)@